version: '2'
services:
  web:
    image: kratika1/web-apps1.1
    ports:
    - "8085:8080"
  db:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_USER=root
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=demodb
